# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

Metrics/MethodLength:
  Max: 25
  Exclude:
    - 'spec/**/*'          # Ignore long methods in specs
  CountComments: false     # Ignore comments in line count
